import type { CrmLead } from "./types";

export const crmLeadsSeed: CrmLead[] = [
  {
    id: "lead-001",
    leadNumber: "LD-2026-0042",
    name: "Rahim Ahmed",
    company: "Metro Retail Ltd",
    email: "rahim@metroretail.bd",
    phone: "+880 1712 345678",
    source: "website",
    status: "qualified",
    score: 86,
    ownerId: "karim",
    ownerName: "Karim Hassan",
    expectedValue: 2_400_000,
    lastActivityAt: "2026-06-19T09:00:00Z",
    lastActivityRelative: "2h ago",
    tags: ["enterprise", "hot"],
    createdAt: "2026-06-01",
    title: "Procurement Head",
    notes: "Interested in bulk apparel order for 12 outlets.",
  },
  {
    id: "lead-002",
    leadNumber: "LD-2026-0041",
    name: "Sadia Khan",
    company: "GreenMart Superstores",
    email: "sadia.k@greenmart.com",
    phone: "+880 1811 223344",
    source: "referral",
    status: "contacted",
    score: 72,
    ownerId: "sadia",
    ownerName: "Sadia Akter",
    expectedValue: 890_000,
    lastActivityAt: "2026-06-18T14:00:00Z",
    lastActivityRelative: "1d ago",
    tags: ["retail"],
    createdAt: "2026-05-28",
    title: "Category Manager",
  },
  {
    id: "lead-003",
    leadNumber: "LD-2026-0040",
    name: "Karim Hossain",
    company: "TechHub Ltd",
    email: "karim@techhub.io",
    phone: "+880 1612 998877",
    source: "linkedin",
    status: "new",
    score: 58,
    ownerId: "nadia",
    ownerName: "Nadia Chowdhury",
    expectedValue: 650_000,
    lastActivityAt: "2026-06-19T06:00:00Z",
    lastActivityRelative: "5h ago",
    tags: ["b2b"],
    createdAt: "2026-06-18",
  },
  {
    id: "lead-004",
    leadNumber: "LD-2026-0039",
    name: "Nusrat Jahan",
    company: "UrbanWear Retail",
    email: "nusrat@urbanwear.bd",
    phone: "+880 1911 556677",
    source: "trade_show",
    status: "converted",
    score: 91,
    ownerId: "farhana",
    ownerName: "Farhana Rahman",
    expectedValue: 1_560_000,
    lastActivityAt: "2026-06-17T10:00:00Z",
    lastActivityRelative: "2d ago",
    tags: ["converted"],
    createdAt: "2026-05-15",
  },
  {
    id: "lead-005",
    leadNumber: "LD-2026-0038",
    name: "Tanvir Islam",
    company: "FreshFoods Co",
    email: "tanvir@freshfoods.bd",
    phone: "+880 1711 445566",
    source: "cold_call",
    status: "lost",
    score: 34,
    ownerId: "karim",
    ownerName: "Karim Hassan",
    expectedValue: 320_000,
    lastActivityAt: "2026-06-10T08:00:00Z",
    lastActivityRelative: "9d ago",
    tags: [],
    createdAt: "2026-05-20",
  },
  {
    id: "lead-006",
    leadNumber: "LD-2026-0037",
    name: "Ayesha Rahman",
    company: "StylePoint Fashion",
    email: "ayesha@stylepoint.bd",
    phone: "+880 1812 334455",
    source: "email_campaign",
    status: "new",
    score: 67,
    ownerId: "sadia",
    ownerName: "Sadia Akter",
    expectedValue: 480_000,
    lastActivityAt: "2026-06-19T07:30:00Z",
    lastActivityRelative: "4h ago",
    tags: ["fashion"],
    createdAt: "2026-06-17",
  },
  {
    id: "lead-007",
    leadNumber: "LD-2026-0036",
    name: "Imran Chowdhury",
    company: "BuildMart Hardware",
    email: "imran@buildmart.bd",
    phone: "+880 1611 778899",
    source: "website",
    status: "contacted",
    score: 74,
    ownerId: "nadia",
    ownerName: "Nadia Chowdhury",
    expectedValue: 1_100_000,
    lastActivityAt: "2026-06-16T11:00:00Z",
    lastActivityRelative: "3d ago",
    tags: ["hardware"],
    createdAt: "2026-06-05",
  },
  {
    id: "lead-008",
    leadNumber: "LD-2026-0035",
    name: "Farzana Akter",
    company: "MediCare Supplies",
    email: "farzana@medicare.bd",
    phone: "+880 1713 112233",
    source: "referral",
    status: "qualified",
    score: 83,
    ownerId: "farhana",
    ownerName: "Farhana Rahman",
    expectedValue: 920_000,
    lastActivityAt: "2026-06-18T16:00:00Z",
    lastActivityRelative: "18h ago",
    tags: ["healthcare"],
    createdAt: "2026-06-02",
  },
];

export function getCrmLeadById(id: string) {
  return crmLeadsSeed.find((l) => l.id === id);
}

export function countCrmLeadsByStatus(leads: CrmLead[]) {
  const counts: Record<string, number> = { all: leads.length, open: 0 };
  for (const s of ["new", "contacted", "qualified", "converted", "lost"] as const) {
    counts[s] = leads.filter((l) => l.status === s).length;
  }
  counts.open = leads.filter((l) => !["converted", "lost"].includes(l.status)).length;
  return counts;
}

export const crmDashboardKpis = {
  leadSummary: { label: "Open Leads", value: "42", change: "+9 this week", up: true },
  pipelineValue: { label: "Pipeline Value", value: "৳ 18.6M", change: "+14%", up: true },
  conversionRate: { label: "Conversion Rate", value: "28%", change: "−1.2pp", up: false },
};
